#!/bin/bash
#
# Automated setup script for Spark VTuber
# Installs dependencies and configures the environment using UV
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_command() {
    if command -v $1 &> /dev/null; then
        log_info "$1 is installed"
        return 0
    else
        log_warn "$1 is not installed"
        return 1
    fi
}

# Banner
echo "================================================"
echo "  Spark VTuber Setup Script"
echo "  Setting up environment with UV"
echo "================================================"
echo ""

# Check if running on Linux
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    log_error "This script is designed for Linux. You're on $OSTYPE"
    log_warn "Please follow manual setup instructions in docs/SETUP.md"
    exit 1
fi

# Step 1: Check system dependencies
log_info "Checking system dependencies..."

MISSING_DEPS=()

if ! check_command git; then MISSING_DEPS+=(git); fi
if ! check_command curl; then MISSING_DEPS+=(curl); fi
if ! check_command wget; then MISSING_DEPS+=(wget); fi
if ! check_command python3; then MISSING_DEPS+=(python3); fi

if [ ${#MISSING_DEPS[@]} -ne 0 ]; then
    log_error "Missing required dependencies: ${MISSING_DEPS[*]}"
    log_info "Install with: sudo apt install ${MISSING_DEPS[*]}"
    exit 1
fi

# Check Python version
PYTHON_VERSION=$(python3 --version | cut -d' ' -f2 | cut -d'.' -f1,2)
REQUIRED_VERSION="3.10"

if (( $(echo "$PYTHON_VERSION < $REQUIRED_VERSION" | bc -l) )); then
    log_error "Python $REQUIRED_VERSION+ required, found $PYTHON_VERSION"
    exit 1
fi

log_info "Python version: $PYTHON_VERSION ✓"

# Step 2: Check CUDA
log_info "Checking CUDA installation..."

if check_command nvidia-smi; then
    CUDA_VERSION=$(nvidia-smi | grep "CUDA Version" | awk '{print $9}')
    log_info "CUDA Version: $CUDA_VERSION ✓"
else
    log_warn "nvidia-smi not found - GPU acceleration may not work"
    log_warn "Install NVIDIA drivers: sudo apt install nvidia-driver-545"
fi

# Step 3: Install UV if needed
log_info "Checking UV package manager..."

if ! check_command uv; then
    log_info "Installing UV..."
    curl -LsSf https://astral.sh/uv/install.sh | sh

    # Add to PATH for current session
    export PATH="$HOME/.cargo/bin:$PATH"

    # Add to shell config if not already there
    if ! grep -q 'cargo/bin' ~/.bashrc; then
        echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
        log_info "Added UV to ~/.bashrc"
    fi

    # Verify installation
    if command -v uv &> /dev/null; then
        log_info "UV installed successfully: $(uv --version)"
    else
        log_error "UV installation failed"
        exit 1
    fi
else
    log_info "UV already installed: $(uv --version) ✓"
fi

# Step 4: Create virtual environment
log_info "Creating Python virtual environment..."

if [ ! -d ".venv" ]; then
    uv venv --python 3.10
    log_info "Virtual environment created"
else
    log_info "Virtual environment already exists"
fi

# Step 5: Activate virtual environment
log_info "Activating virtual environment..."
source .venv/bin/activate

# Step 6: Install Python dependencies
log_info "Installing Python dependencies (this may take 10-20 minutes)..."
log_warn "Large models will be downloaded during first run"

# Install with UV
uv pip install -e ".[dev]"

log_info "Dependencies installed successfully"

# Step 7: Create necessary directories
log_info "Creating data directories..."
mkdir -p data/chroma
mkdir -p logs
mkdir -p models

# Step 8: Setup environment file
if [ ! -f ".env" ]; then
    log_info "Creating .env configuration file..."

    cat > .env << 'EOL'
# Spark VTuber Configuration
# Generated by setup.sh

# LLM Configuration
LLM__MODEL_NAME=Qwen/Qwen3-30B-A3B-Instruct
LLM__QUANTIZATION=awq
LLM__GPU_MEMORY_UTILIZATION=0.70
LLM__CONTEXT_LENGTH=8192
LLM__MAX_TOKENS=2048
LLM__TEMPERATURE=0.7

# TTS Configuration
TTS__ENGINE=coqui
TTS__MODEL_NAME=tts_models/en/ljspeech/tacotron2-DDC
TTS__SAMPLE_RATE=22050
TTS__STREAMING=true

# STT Configuration
STT__MODEL_SIZE=large-v3
STT__DEVICE=cuda
STT__COMPUTE_TYPE=float16
STT__LANGUAGE=en
STT__VAD_ENABLED=true

# Memory Configuration
MEMORY__CHROMA_PERSIST_DIR=./data/chroma
MEMORY__EMBEDDING_MODEL=all-MiniLM-L6-v2
MEMORY__MAX_MEMORIES=10000
MEMORY__RETRIEVAL_TOP_K=5

# Avatar Configuration
AVATAR__VTUBE_STUDIO_HOST=localhost
AVATAR__VTUBE_STUDIO_PORT=8001
AVATAR__PLUGIN_NAME=SparkVTuber
AVATAR__LIP_SYNC_ENABLED=true
AVATAR__EXPRESSION_ENABLED=true

# Personality Configuration
PERSONALITY__PRIMARY_NAME=Spark
PERSONALITY__SECONDARY_NAME=Shadow
PERSONALITY__SWITCH_COOLDOWN=5.0

# Chat Configuration
CHAT__TWITCH_ENABLED=false
CHAT__TWITCH_CHANNEL=
CHAT__TWITCH_OAUTH_TOKEN=
CHAT__MESSAGE_QUEUE_SIZE=100
CHAT__RATE_LIMIT_PER_MINUTE=20

# Game Configuration
GAME__MINECRAFT_ENABLED=false
GAME__MINECRAFT_HOST=localhost
GAME__MINECRAFT_PORT=25565
GAME__MINECRAFT_USERNAME=SparkVTuber

# App Configuration
DEBUG=false
LOG_LEVEL=INFO
EOL

    log_info ".env file created"
    log_warn "Edit .env to configure Twitch, personalities, etc."
else
    log_info ".env file already exists (not overwriting)"
fi

# Step 9: Create .env.example if it doesn't exist
if [ ! -f ".env.example" ]; then
    cp .env .env.example
    log_info "Created .env.example"
fi

# Step 10: Run verification
log_info "Verifying installation..."

# Check if spark-vtuber CLI works
if uv run spark-vtuber version &> /dev/null; then
    VERSION=$(uv run spark-vtuber version)
    log_info "CLI works: $VERSION ✓"
else
    log_error "CLI verification failed"
    exit 1
fi

# Final message
echo ""
echo "================================================"
log_info "Setup complete! 🎉"
echo "================================================"
echo ""
echo "Next steps:"
echo ""
echo "1. Activate the virtual environment:"
echo "   source .venv/bin/activate"
echo ""
echo "2. (Optional) Edit configuration:"
echo "   nano .env"
echo ""
echo "3. Test the LLM (downloads model on first run):"
echo "   uv run spark-vtuber test-llm \"Hello!\""
echo ""
echo "4. Run the system in test mode:"
echo "   uv run spark-vtuber run --no-chat --no-avatar --no-game"
echo ""
echo "5. For full setup instructions, see:"
echo "   docs/SETUP.md"
echo ""
echo "6. Review the audit report for known issues:"
echo "   docs/AUDIT_REPORT.md"
echo ""

log_warn "Models will download automatically on first use (~40GB for LLM)"
log_warn "This may take 1-2 hours depending on your internet connection"
echo ""

# Exit successfully
exit 0
